SpeechIT/urls.py
from django.urls import path
from .views import index, to_speech, audio_page

app_name = 'SpeechIT'
urlpatterns = [
    path('', index, name='index'),
    path('spoken/', to_speech, name='to_speech'),
    path('spoken/<str:hash_>', audio_page, name='audio_page'),
]

TextToSpeech/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(path('', include('SpeechIT.urls')))
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SpeechIT/models.py
from platform import version

from django.db import models
from django.utils import timezone
from datetime import timedelta


class Post(models.Model):
    text = models.TextField(verbose_name='Text')
    lang = models.CharField(verbose_name='language', max_length=2, default='ru')
    hash_str = models.CharField(verbose_name='hash', max_length=128, editable=None)
    ip = models.CharField(verbose_name='from IP', max_length=15)
    date = models.DateTimeField(verbose_name='post date', auto_now=True)
    path = models.TextField(verbose_name='path', editable=None, blank=True)

    def __str__(self):
        return self.text

    def need_delete(self):
        return self.date <= timezone.now() - timedelta(days=1)

    class Meta:
        verbose_name = 'Text'
        verbose_name_plural = 'Texts'

SpeechIT/views.py
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.http import HttpResponseRedirect
from gtts import gTTS
from .models import Post
import hashlib
import os


def get_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[-1].strip()
    else:
        return request.META.get('REMOTE_ADDR')


def create_mp3(text, lang: str):
    mp3 = None
    if text:
        mp3 = gTTS(text=text, lang=lang)
    return mp3


def get_hash(text: str) -> str:
    return hashlib.sha512(text.strip().upper().encode()).hexdigest()


def del_old():
    posts = Post.objects.all()
    for post in posts:
        if post.need_delete():
            if os.path.isfile(post.path):
                os.remove(post.path)
            post.delete()


def index(request):
    del_old()
    return render(request, 'SpeechIT/homepage.html', {'path': request.path})


def to_speech(request):
    text_data = request.POST['qtext']
    text_lang = request.POST['lang']
    hash_digit = get_hash(text_data)
    ip = get_ip(request)
    Post.objects.update_or_create(hash_str=hash_digit, defaults={'text': text_data, 'lang': text_lang,
                                                                 'ip': ip, 'date': timezone.now(),
                                                                 'path': os.path.join(settings.MEDIA_ROOT,
                                                                                      f'{hash_digit}.mp3')})
    return HttpResponseRedirect(reverse('SpeechIT:audio_page', args=(hash_digit,)))


def audio_page(request, hash_):
    from_db = Post.objects.get(hash_str=hash_)
    if not os.path.isfile(from_db.path):
        file = gTTS(text=from_db.text, lang=from_db.lang)
        file.save(from_db.path)

    return render(request, 'SpeechIT/download.html',
                  {'db': from_db, 'media': f"{settings.MEDIA_URL}{hash_}.mp3"})

templates/SpeechIT/download.html
{% extends 'SpeechIT/template.html' %}

{% load static %}
{% load i18n %}

{% block title %}
{% trans "We save audio message for you" %}
{% endblock %}

{% block url_info %}
{% trans "We save audio message for you" %}
{% endblock %}


{% block content %}
    <a href="/" title="{% trans "Back to HomePage" %}"><img src="{% static "SpeechIT/img/back.png" %}" alt="{% trans "back" %}"> </a>
    <div class="content">
    <audio src="{{ media }}" controls>
    {% trans "Tag audio not work in your browser" %}
    </audio>



    <hr>
    <h2>{% trans "Share" %}</h2>
    <a href="https://telegram.me/share/url?url={{ request.build_absolute_uri }}&text={{ db.text }}"><img src="{% static 'SpeechIT/img/telegram.png' %}" class="social"></a>
    <a href="viber://forward?text={{ request.build_absolute_uri }}"><img src="{% static 'SpeechIT/img/viber.png' %}" class="social"></a>
    <a href="https://vk.com/share.php?url={{ request.build_absolute_uri }}&text={{ db.text }}" target="_blank"><img src="{% static 'SpeechIT/img/vk.png' %}" class="social"></a>
</div>
{% endblock %}

templates/SpeechIT/homepage.html
{% extends 'SpeechIT/template.html' %}

{% load static %}
{% load i18n %}

{% block url_info %}
    {{ path }}
{% endblock %}

{% block title %}
    {% trans "Text to Speech - Homepage" %}
{% endblock %}

{% block content %}
    <div class="content">
        <a href="/"><img src="{% static 'SpeechIT/img/cloud.png' %}" alt="img"></a>

            <form method="post" action="{% url 'SpeechIT:to_speech' %}">
                {% csrf_token %}
                <select name="lang" class="obj-content">
                    <option value="en" selected>English</option>
                    <option value="ru">Русский</option>
                    <option value="be">Беларуская</option>
                    <option value="uk">Українська</option>
                    <option value="de">Deutsch</option>
                    <option value="it">Italiano</option>
                    <option value="es">Español</option>
                    <option value="zh">中文</option>
                </select>
                <textarea class="obj-content" name="qtext" required placeholder="{% trans "Write text here..." %}" id="memo"></textarea>
                <div id="count">{% trans "Symbols count: " %}0</div>
                <button type="submit" class="button">{% trans "Convert IT" %}</button>
            </form>
        </div>

<script>
memo.oninput = memo.onkeyp = memo.onchange = function(){
    var len = this.value.length;
    document.getElementById('count').innerText = "{% trans 'Symbols count: ' %}" + len;
}
</script>

{% endblock %}

templates/SpeechIT/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load static i18n %}
    <meta charset="UTF-8">
    <meta property="og:site_name" content="Speech IT">
    <meta property="og:title" content="{% trans "Text to Speech" %}">
    <meta property="og:url" content="{% block url_info %} 127/0/0/1 {% endblock %}">
    <meta property="og:description" content="{% trans "This service make text to audio" %}">
    <meta property="og:image" content="{% static 'SpeechIT/img/cloud.png' %}">
    <title>{% block title %} {% trans "Text to Speech" %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'SpeechIT/css/template.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>